export const RACKET_BRANDS = [
  'Babolat',
  'Dunlop',
  'Head',
  'Prince',
  'Tecnifibre',
  'Volkl',
  'Wilson',
  'Yonex',
];

export const RACKET_MODELS = {
  Babolat: [
    'Boost Aero',
    'Boost Drive',
    'Pure Aero',
    'Pure Aero 98',
    'Pure Aero 98+',
    'Pure Aero Lite',
    'Pure Aero Plus',
    'Pure Aero Team',
    'Pure Drive',
    'Pure Drive 98',
    'Pure Drive 100',
    'Pure Drive Lite',
    'Pure Drive Plus',
    'Pure Drive Team',
    'Pure Drive VS',
    'Pure Strike',
    'Pure Strike 16x19',
    'Pure Strike 18x20',
    'Pure Strike 98',
    'Pure Strike 100',
    'Pure Strike Lite',
    'Pure Strike Team',
    'Pure Strike VS',
  ],
  Dunlop: [
    'CX 200',
    'CX 200 LS',
    'CX 200 OS',
    'CX 200 Tour',
    'CX 400',
    'CX 400 Tour',
    'FX 500',
    'FX 500 LS',
    'FX 500 Tour',
    'FX 700',
    'SX 300',
    'SX 300 LS',
    'SX 300 Tour',
  ],
  Head: [
    'Boom MP',
    'Boom Pro',
    'Boom Team',
    'Extreme MP',
    'Extreme Pro',
    'Extreme S',
    'Extreme Team',
    'Extreme Tour',
    'Instinct Lite',
    'Instinct MP',
    'Instinct Pro',
    'Instinct S',
    'Prestige Mid',
    'Prestige MP',
    'Prestige Pro',
    'Prestige Tour',
    'Radical MP',
    'Radical OS',
    'Radical Pro',
    'Radical S',
    'Speed MP',
    'Speed Pro',
    'Speed PWR',
    'Speed S',
    'Speed Team',
  ],
  Prince: [
    'Beast 98',
    'Beast 100',
    'Beast 104',
    'Phantom 100',
    'Textreme Beast',
    'Textreme Tour 95',
    'Textreme Tour 100',
  ],
  Tecnifibre: [
    'T-Fit 255',
    'T-Fit 265',
    'T-Fit 275',
    'TFight 265',
    'TFight 275',
    'TFight 280',
    'TFight 295',
    'TFight 300',
    'TFight 305',
    'TFight 315',
    'TFight 325',
    'TFight DC 300',
    'TFight DC 305',
    'TFight RS 300',
    'TFight RS 305',
  ],
  Volkl: [
    'V-Cell 7',
    'V-Cell 8',
    'V-Cell 9',
    'V-Feel 5',
    'V-Feel 7',
    'V-Sense 1',
    'V-Sense 5',
  ],
  Wilson: [
    'Blade 98 (16x19)',
    'Blade 98 (18x20)',
    'Blade 98L',
    'Blade 100',
    'Blade 100L',
    'Blade 100UL',
    'Burn 100',
    'Burn 100S',
    'Clash 98',
    'Clash 100',
    'Clash 100 Pro',
    'Clash 100L',
    'Clash 100UL',
    'Pro Staff 97',
    'Pro Staff 97L',
    'Pro Staff 97v13',
    'Pro Staff RF97',
    'Shift 99',
    'Shift 99 Pro',
    'Ultra 100',
    'Ultra 108',
    'Ultra Tour 95',
    'Ultra Tour 100',
  ],
  Yonex: [
    'EZONE 98',
    'EZONE 98L',
    'EZONE 100',
    'EZONE 100L',
    'EZONE 105',
    'EZONE 108',
    'PERCEPT 97',
    'PERCEPT 97D',
    'PERCEPT 100',
    'PERCEPT 100D',
    'VCORE 95',
    'VCORE 98',
    'VCORE 100',
    'VCORE 100L',
    'VCORE Pro 97',
    'VCORE Pro 97D',
    'VCORE Pro 100',
  ],
};

export const HEAD_SIZES = [95, 96, 97, 98, 99, 100, 101, 102, 103, 104];

export const GRIP_SIZES = [
  { value: 'L1 (4 1/8")', label: '1그립 (4 1/8")' },
  { value: 'L2 (4 1/4")', label: '2그립 (4 1/4")' },
  { value: 'L3 (4 3/8")', label: '3그립 (4 3/8")' },
  { value: 'L4 (4 1/2")', label: '4그립 (4 1/2")' },
  { value: 'L5 (4 5/8")', label: '5그립 (4 5/8")' },
];

export const RACKET_WEIGHTS = Array.from({ length: 15 }, (_, i) => 260 + i * 5);
