export const STRING_BRANDS = [
  'Dunlop',
  'Diadem',
  'Luxilon',
  'Robin Soderling',
  'Weiss Cannon',
  'Babolat',
  'Signum Pro',
  'Solinco',
  'Yonex',
  'Wilson',
  'Isospeed',
  'Zons',
  'Mayami',
  'Top Spin',
  'Tecnifibre',
  'Toro Line',
  'Tourna',
  'Head',
  'Grapplesnake',
  'MSV',
];

export const STRING_MODELS = {
  Dunlop: [
    'Black Widow',
    'Silk',
    'Explosive',
    'Explosive Spin',
    'Explosive Tour',
  ],
  Diadem: [
    'Elite XT',
    'Flash',
    'Pro X',
    'Solstice Black',
    'Solstice Power',
  ],
  Luxilon: [
    '4G',
    '4G Desert Bronze',
    '4G Rough',
    '4G Black',
    'LXN Smart',
    'ALU Power',
    'ALU Power Rough',
    'ALU Power Vibe',
    'LXN ECO Spin',
    'LXN ECO Rough',
    'LXN ECO Power',
    'Element',
  ],
  'Robin Soderling': [
    'New York',
    'Lyon',
    'Paris',
  ],
  'Weiss Cannon': [
    '6 Star',
    'New Element',
    'Red Ghost',
    'Mosquito Bite',
    'Scorpion',
    'Silverstring',
    'Ultra Cable',
    'Turbo Twist',
    'Principle',
    'Fire Stroke',
  ],
  Babolat: [
    'Hurricane',
    'RPM Blast',
    'RPM Blast Rough',
    'RPM Soft',
    'RPM Team',
    'RPM Power',
    'Addiction',
    'VS Touch',
  ],
  'Signum Pro': [
    'Thunderstorm',
    'Outbreak',
    'X-Perience',
    'Firestorm',
    'Polaris',
    'Poly Plasma',
    'Hyperion',
  ],
  Solinco: [
    'Mach-10',
    'Hyper-G',
    'Hyper-G Soft',
    'Confidential',
    'Tour Bite',
  ],
  Yonex: [
    'Poly Tour Rev',
    'Poly Tour Strike',
    'Poly Tour Spin',
    'Poly Tour Fire',
    'Poly Tour Force',
    'Poly Tour Pro',
  ],
  Wilson: [
    'NXT',
    'Revolve',
    'Sensation',
  ],
  Isospeed: [
    'Rexxer',
    'Baseline Speed',
    'Baseline Spin',
    'Baseline Spin+Speed',
    'Black Fire',
    'Energy',
    'Control',
    'Cream',
    'Professional',
  ],
  Zons: [
    'MaxiFiber Tour',
    'Spin Plus',
    'Phantom Break',
    'Polymo Thunder',
    'Heptabolt',
    'Polymo Tour',
    'Polymo Hexsplosion',
  ],
  Mayami: [
    'Big Spin',
    'Hepta Power',
    'Hit Pro',
    'Tour Hex',
  ],
  'Top Spin': [
    'Max Rotation',
    'Cyber Blue',
    'Cyber Flash',
    'Sensus Rotation',
    'Top Rotation',
    'Pure Concept',
  ],
  Tecnifibre: [
    'HDX Tour',
    'X-One Biphase',
    'Duramix',
    'Red Code',
    'Razor Soft',
    'Razor Code',
    'Multi Feel',
    'Black Code 4S',
    'Black Code',
    'Ice Code',
    'Triax',
    'Pro Red Code Wax',
  ],
  'Toro Line': [
    'Wasabi',
    'Snapper',
    'Toro Toro',
    'O-Toro Tour',
    'O-Toro Spin',
  ],
  Tourna: [
    'Big Hitter Black7',
    'Big Hitter Black Zone',
    'Big Hitter Blue Rough',
    'Big Hitter Silver 7',
    'Premium Poly',
  ],
  Head: [
    'Rip Control',
    'Lynx',
    'Lynx Edge',
    'Lynx Touch',
    'Lynx Tour',
    'Velocity MLT',
    'Sonic Pro',
    'Hawk',
    'Hawk Touch',
    'Hawk Power',
  ],
  Grapplesnake: [
    'Changer',
    'Alpha',
    'Tour M8',
    'Tour Sniper',
  ],
  MSV: [
    'Focus Hepta Twist',
    'Focus HEX',
    'Focus HEX Ultra',
    'Focus HEX Soft',
    'MSV Co Ultra',
  ],
};

export const STRING_COLORS = [
  'Black',
  'White',
  'Natural',
  'Clear',
  'Silver',
  'Gray',
  'Blue',
  'Navy',
  'Green',
  'Neon Green',
  'Yellow',
  'Orange',
  'Red',
  'Pink',
  'Purple',
  'Bronze',
  'Gold',
];

export const STRING_TYPES = [
  'Polyester (Co-Poly)',
  'Polyester (Mono)',
  'Multifilament',
  'Natural Gut',
  'Synthetic Gut',
  'Nylon',
  'Hybrid',
];

export const GAUGE_OPTIONS = [
  { value: '1.10mm (19)', label: '1.10mm (19)' },
  { value: '1.15mm (18)', label: '1.15mm (18)' },
  { value: '1.18mm (18)', label: '1.18mm (18)' },
  { value: '1.20mm (17)', label: '1.20mm (17)' },
  { value: '1.23mm (17)', label: '1.23mm (17)' },
  { value: '1.24mm (17)', label: '1.24mm (17)' },
  { value: '1.25mm (16L)', label: '1.25mm (16L)' },
  { value: '1.27mm (16)', label: '1.27mm (16)' },
  { value: '1.28mm (16)', label: '1.28mm (16)' },
  { value: '1.30mm (16)', label: '1.30mm (16)' },
  { value: '1.35mm (15L)', label: '1.35mm (15L)' },
  { value: '1.40mm (15)', label: '1.40mm (15)' },
];

export const PRIMARY_SHAPES = ['Round', 'Shaped', 'Other'];
export const POLYGON_TYPES = ['4-sided', '5-sided', '6-sided', '7-sided', '8-sided', 'Star-shaped'];

export const ALL_STRING_OPTIONS = Object.entries(STRING_MODELS)
  .flatMap(([brand, models]) => models.map((model) => `${brand} ${model}`))
  .sort((a, b) => a.localeCompare(b));
