export const STRING_DATABASE = [
  {
    id: 'solinco-hyper-g-16l',
    brand: 'Solinco',
    name: 'Hyper-G',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'square',
    stiffness: 74,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '48-54lbs',
    price_band: '$16/세트',
    specs: { power: 6, spin: 10, control: 8, comfort: 5, durability: 8, tension_stability: 7 },
    description: '강한 스핀과 분명한 타구감을 주는 대표적인 스핀형 코폴리입니다. 공격형 베이스라이너에게 특히 잘 맞습니다.',
    tags: ['스핀', '공격형'],
  },
  {
    id: 'solinco-hyper-g-soft-17',
    brand: 'Solinco',
    name: 'Hyper-G Soft',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'square',
    stiffness: 62,
    arm_friendly: true,
    gauge_mm: 1.20,
    gauge_label: '17 (1.20mm)',
    recommended_tension: '46-52lbs',
    price_band: '$17/세트',
    specs: { power: 7, spin: 9, control: 7, comfort: 8, durability: 6, tension_stability: 6 },
    description: '하이퍼-G 계열의 스핀 성향을 유지하면서도 더 부드러운 타구감과 편안함을 제공합니다.',
    tags: ['컴포트', '스핀'],
  },
  {
    id: 'luxilon-alu-power-16l',
    brand: 'Luxilon',
    name: 'ALU Power',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 71,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '48-54lbs',
    price_band: '$19/세트',
    specs: { power: 8, spin: 8, control: 8, comfort: 5, durability: 7, tension_stability: 6 },
    description: '반발력과 타구감의 밸런스가 좋아 투어급 선수부터 동호인까지 폭넓게 쓰는 클래식 코폴리입니다.',
    tags: ['파워', '올라운드'],
  },
  {
    id: 'luxilon-element-16',
    brand: 'Luxilon',
    name: 'Element',
    type: '폴리에스터',
    family: 'multi-mono',
    shape: 'round',
    stiffness: 58,
    arm_friendly: true,
    gauge_mm: 1.30,
    gauge_label: '16 (1.30mm)',
    recommended_tension: '46-52lbs',
    price_band: '$20/세트',
    specs: { power: 7, spin: 7, control: 7, comfort: 9, durability: 7, tension_stability: 7 },
    description: '폴리 계열 중에서도 매우 부드러운 편이라 엘보를 걱정하는 플레이어에게 적합합니다.',
    tags: ['컴포트', '팔친화'],
  },
  {
    id: 'yonex-polytour-pro-125',
    brand: 'Yonex',
    name: 'PolyTour Pro',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 60,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-52lbs',
    price_band: '$15/세트',
    specs: { power: 7, spin: 7, control: 7, comfort: 8, durability: 7, tension_stability: 8 },
    description: '매우 무난하고 안정적인 성향의 코폴리로, 불필요하게 과하지 않은 밸런스를 제공합니다.',
    tags: ['밸런스', '장력유지'],
  },
  {
    id: 'yonex-polytour-rev-125',
    brand: 'Yonex',
    name: 'PolyTour Rev',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'pentagon',
    stiffness: 66,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$17/세트',
    specs: { power: 6, spin: 9, control: 8, comfort: 6, durability: 7, tension_stability: 7 },
    description: '회전량과 컨트롤을 동시에 노리는 유저에게 잘 맞는 현대적인 스핀 폴리입니다.',
    tags: ['스핀', '컨트롤'],
  },
  {
    id: 'head-lynx-tour-125',
    brand: 'Head',
    name: 'Lynx Tour',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'hexagon',
    stiffness: 69,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$16/세트',
    specs: { power: 6, spin: 8, control: 9, comfort: 5, durability: 8, tension_stability: 7 },
    description: '확실한 컨트롤과 단단한 응답성을 원하는 강타자에게 어울리는 폴리입니다.',
    tags: ['컨트롤', '단단함'],
  },
  {
    id: 'head-hawk-touch-125',
    brand: 'Head',
    name: 'Hawk Touch',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 63,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-52lbs',
    price_band: '$18/세트',
    specs: { power: 6, spin: 7, control: 9, comfort: 7, durability: 7, tension_stability: 8 },
    description: '컨트롤 성향이 강하면서도 지나치게 딱딱하지 않아 경기용 세팅으로 활용하기 좋습니다.',
    tags: ['컨트롤', '경기용'],
  },
  {
    id: 'babolat-rpm-blast-17',
    brand: 'Babolat',
    name: 'RPM Blast',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'octagon',
    stiffness: 71,
    arm_friendly: false,
    gauge_mm: 1.20,
    gauge_label: '17 (1.20mm)',
    recommended_tension: '48-55lbs',
    price_band: '$18/세트',
    specs: { power: 6, spin: 9, control: 8, comfort: 5, durability: 7, tension_stability: 6 },
    description: '임팩트가 빠르고 스윙이 큰 플레이어에게 잘 맞는 강한 스핀 계열의 대표작입니다.',
    tags: ['스핀', '공격형'],
  },
  {
    id: 'babolat-rpm-soft-125',
    brand: 'Babolat',
    name: 'RPM Soft',
    type: '폴리에스터',
    family: 'polyamide blend',
    shape: 'round',
    stiffness: 55,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-52lbs',
    price_band: '$17/세트',
    specs: { power: 8, spin: 7, control: 6, comfort: 9, durability: 6, tension_stability: 6 },
    description: '폴리 감성을 어느 정도 유지하면서도 훨씬 부드러운 타구감을 제공하는 편안한 선택지입니다.',
    tags: ['컴포트', '쉬운반발'],
  },
  {
    id: 'wilson-revolve-spin-125',
    brand: 'Wilson',
    name: 'Revolve Spin',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'pentagon',
    stiffness: 67,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '47-54lbs',
    price_band: '$15/세트',
    specs: { power: 6, spin: 9, control: 7, comfort: 6, durability: 7, tension_stability: 6 },
    description: '회전량을 높이면서도 지나치게 무겁지 않은 응답을 원할 때 선택하기 좋은 스핀 특화형 스트링입니다.',
    tags: ['스핀', '현대적'],
  },
  {
    id: 'wilson-revolve-125',
    brand: 'Wilson',
    name: 'Revolve',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 61,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$15/세트',
    specs: { power: 7, spin: 7, control: 7, comfort: 8, durability: 7, tension_stability: 6 },
    description: '부드러운 반발과 적당한 회전, 무난한 컨트롤을 모두 갖춘 밸런스형 코폴리입니다.',
    tags: ['밸런스', '컴포트'],
  },
];
