export const STRING_DATABASE = [
  {
    id: 'solinco-hyper-g-16l',
    brand: 'Solinco',
    name: 'Hyper-G',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'square',
    stiffness: 74,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '48-54lbs',
    price_band: '$16/세트',
    specs: { power: 6, spin: 10, control: 8, comfort: 5, durability: 8, tension_stability: 7 },
    description: '강한 스핀과 분명한 타구감을 주는 대표적인 스핀형 코폴리입니다. 공격형 베이스라이너에게 특히 잘 맞습니다.',
    tags: ['스핀', '공격형'],
  },
  {
    id: 'solinco-hyper-g-soft-17',
    brand: 'Solinco',
    name: 'Hyper-G Soft',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'square',
    stiffness: 62,
    arm_friendly: true,
    gauge_mm: 1.20,
    gauge_label: '17 (1.20mm)',
    recommended_tension: '46-52lbs',
    price_band: '$17/세트',
    specs: { power: 7, spin: 9, control: 7, comfort: 8, durability: 6, tension_stability: 6 },
    description: '하이퍼-G 계열의 스핀 성향을 유지하면서도 더 부드러운 타구감과 편안함을 제공합니다.',
    tags: ['컴포트', '스핀'],
  },
  {
    id: 'luxilon-alu-power-16l',
    brand: 'Luxilon',
    name: 'ALU Power',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 71,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '48-54lbs',
    price_band: '$19/세트',
    specs: { power: 8, spin: 8, control: 8, comfort: 5, durability: 7, tension_stability: 6 },
    description: '반발력과 타구감의 밸런스가 좋아 투어급 선수부터 동호인까지 폭넓게 쓰는 클래식 코폴리입니다.',
    tags: ['파워', '올라운드'],
  },
  {
    id: 'luxilon-element-16',
    brand: 'Luxilon',
    name: 'Element',
    type: '폴리에스터',
    family: 'multi-mono',
    shape: 'round',
    stiffness: 58,
    arm_friendly: true,
    gauge_mm: 1.30,
    gauge_label: '16 (1.30mm)',
    recommended_tension: '46-52lbs',
    price_band: '$20/세트',
    specs: { power: 7, spin: 7, control: 7, comfort: 9, durability: 7, tension_stability: 7 },
    description: '폴리 계열 중에서도 매우 부드러운 편이라 엘보를 걱정하는 플레이어에게 적합합니다.',
    tags: ['컴포트', '팔친화'],
  },
  {
    id: 'yonex-polytour-pro-125',
    brand: 'Yonex',
    name: 'PolyTour Pro',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 60,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-52lbs',
    price_band: '$15/세트',
    specs: { power: 7, spin: 7, control: 7, comfort: 8, durability: 7, tension_stability: 8 },
    description: '매우 무난하고 안정적인 성향의 코폴리로, 불필요하게 과하지 않은 밸런스를 제공합니다.',
    tags: ['밸런스', '장력유지'],
  },
  {
    id: 'yonex-polytour-rev-125',
    brand: 'Yonex',
    name: 'PolyTour Rev',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'pentagon',
    stiffness: 66,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$17/세트',
    specs: { power: 6, spin: 9, control: 8, comfort: 6, durability: 7, tension_stability: 7 },
    description: '회전량과 컨트롤을 동시에 노리는 유저에게 잘 맞는 현대적인 스핀 폴리입니다.',
    tags: ['스핀', '컨트롤'],
  },
  {
    id: 'head-lynx-tour-125',
    brand: 'Head',
    name: 'Lynx Tour',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'hexagon',
    stiffness: 69,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$16/세트',
    specs: { power: 6, spin: 8, control: 9, comfort: 5, durability: 8, tension_stability: 7 },
    description: '확실한 컨트롤과 단단한 응답성을 원하는 강타자에게 어울리는 폴리입니다.',
    tags: ['컨트롤', '단단함'],
  },
  {
    id: 'head-hawk-touch-125',
    brand: 'Head',
    name: 'Hawk Touch',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 63,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-52lbs',
    price_band: '$18/세트',
    specs: { power: 6, spin: 7, control: 9, comfort: 7, durability: 7, tension_stability: 8 },
    description: '컨트롤 성향이 강하면서도 지나치게 딱딱하지 않아 경기용 세팅으로 활용하기 좋습니다.',
    tags: ['컨트롤', '경기용'],
  },
  {
    id: 'babolat-rpm-blast-17',
    brand: 'Babolat',
    name: 'RPM Blast',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'octagon',
    stiffness: 71,
    arm_friendly: false,
    gauge_mm: 1.20,
    gauge_label: '17 (1.20mm)',
    recommended_tension: '48-55lbs',
    price_band: '$18/세트',
    specs: { power: 6, spin: 9, control: 8, comfort: 5, durability: 7, tension_stability: 6 },
    description: '임팩트가 빠르고 스윙이 큰 플레이어에게 잘 맞는 강한 스핀 계열의 대표작입니다.',
    tags: ['스핀', '공격형'],
  },
  {
    id: 'babolat-rpm-soft-125',
    brand: 'Babolat',
    name: 'RPM Soft',
    type: '폴리에스터',
    family: 'polyamide blend',
    shape: 'round',
    stiffness: 55,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-52lbs',
    price_band: '$17/세트',
    specs: { power: 8, spin: 7, control: 6, comfort: 9, durability: 6, tension_stability: 6 },
    description: '폴리 감성을 어느 정도 유지하면서도 훨씬 부드러운 타구감을 제공하는 편안한 선택지입니다.',
    tags: ['컴포트', '쉬운반발'],
  },
  {
    id: 'wilson-revolve-spin-125',
    brand: 'Wilson',
    name: 'Revolve Spin',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'pentagon',
    stiffness: 67,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '47-54lbs',
    price_band: '$15/세트',
    specs: { power: 6, spin: 9, control: 7, comfort: 6, durability: 7, tension_stability: 6 },
    description: '회전량을 높이면서도 지나치게 무겁지 않은 응답을 원할 때 선택하기 좋은 스핀 특화형 스트링입니다.',
    tags: ['스핀', '현대적'],
  },
  {
    id: 'wilson-revolve-125',
    brand: 'Wilson',
    name: 'Revolve',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 61,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$15/세트',
    specs: { power: 7, spin: 7, control: 7, comfort: 8, durability: 7, tension_stability: 6 },
    description: '부드러운 반발과 적당한 회전, 무난한 컨트롤을 모두 갖춘 밸런스형 코폴리입니다.',
    tags: ['밸런스', '컴포트'],
  },
  {
    id: 'tecnifibre-black-code-4s-125',
    brand: 'Tecnifibre',
    name: 'Black Code 4S',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'square',
    stiffness: 70,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '$17/세트',
    specs: { power: 6, spin: 10, control: 8, comfort: 5, durability: 8, tension_stability: 7 },
    description: '사각형 단면이 만들어내는 강렬한 스핀과 명확한 타구 응답감이 특징인 스핀 특화 코폴리입니다.',
    tags: ['스핀', '컨트롤'],
  },
  {
    id: 'tecnifibre-ice-code-125',
    brand: 'Tecnifibre',
    name: 'Ice Code',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 56,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-51lbs',
    price_band: '$18/세트',
    specs: { power: 8, spin: 6, control: 7, comfort: 9, durability: 7, tension_stability: 7 },
    description: '폴리 중에서도 매우 부드러운 타구감과 높은 반발력을 동시에 갖춰 장시간 플레이에도 피로가 적습니다.',
    tags: ['컴포트', '팔친화'],
  },
  {
    id: 'signum-pro-tornado-125',
    brand: 'Signum Pro',
    name: 'Tornado',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'pentagon',
    stiffness: 72,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '47-54lbs',
    price_band: '$14/세트',
    specs: { power: 6, spin: 9, control: 8, comfort: 5, durability: 9, tension_stability: 8 },
    description: '독일 브랜드 특유의 내구성과 일관된 스핀 성능을 겸비한 가성비 우수 스트링입니다.',
    tags: ['스핀', '내구성'],
  },
  {
    id: 'volkl-cyclone-125',
    brand: 'Völkl',
    name: 'Cyclone',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'star',
    stiffness: 70,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '47-54lbs',
    price_band: '$13/세트',
    specs: { power: 6, spin: 10, control: 7, comfort: 5, durability: 8, tension_stability: 7 },
    description: '별 모양 단면이 탁월한 스핀을 만들어내는 가성비 최강 스핀 스트링으로, 강한 스윙의 플레이어에게 적합합니다.',
    tags: ['스핀', '가성비'],
  },
  {
    id: 'kirschbaum-pro-line-ii-125',
    brand: 'Kirschbaum',
    name: 'Pro Line II',
    type: '폴리에스터',
    family: 'mono',
    shape: 'round',
    stiffness: 73,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '48-54lbs',
    price_band: '$12/세트',
    specs: { power: 5, spin: 7, control: 9, comfort: 4, durability: 10, tension_stability: 9 },
    description: '업계 최고 수준의 내구성과 장력 유지로 잦은 스트링 교체를 원치 않는 플레이어에게 최적입니다.',
    tags: ['내구성', '장력유지'],
  },
  {
    id: 'wilson-nxt-16',
    brand: 'Wilson',
    name: 'NXT',
    type: '멀티필라멘트',
    family: 'multifilament',
    shape: 'round',
    stiffness: 44,
    arm_friendly: true,
    gauge_mm: 1.30,
    gauge_label: '16 (1.30mm)',
    recommended_tension: '50-60lbs',
    price_band: '$19/세트',
    specs: { power: 9, spin: 5, control: 6, comfort: 10, durability: 5, tension_stability: 5 },
    description: '내추럴 거트에 가장 근접한 타구감을 가진 멀티필라멘트로, 팔 보호가 최우선인 플레이어에게 적합합니다.',
    tags: ['컴포트', '팔친화', '멀티'],
  },
  {
    id: 'tecnifibre-x-one-biphase-17',
    brand: 'Tecnifibre',
    name: 'X-One Biphase',
    type: '멀티필라멘트',
    family: 'multifilament',
    shape: 'round',
    stiffness: 46,
    arm_friendly: true,
    gauge_mm: 1.24,
    gauge_label: '17 (1.24mm)',
    recommended_tension: '50-60lbs',
    price_band: '$22/세트',
    specs: { power: 9, spin: 5, control: 7, comfort: 10, durability: 5, tension_stability: 6 },
    description: '뛰어난 감각과 반발, 팔 친화적인 타구감을 원하는 플레이어에게 추천하는 고급 멀티필라멘트입니다.',
    tags: ['컴포트', '팔친화', '멀티'],
  },
  {
    id: 'babolat-vs-touch-16',
    brand: 'Babolat',
    name: 'VS Touch',
    type: '내추럴 거트',
    family: 'natural gut',
    shape: 'round',
    stiffness: 41,
    arm_friendly: true,
    gauge_mm: 1.30,
    gauge_label: '16 (1.30mm)',
    recommended_tension: '53-63lbs',
    price_band: '$55/세트',
    specs: { power: 10, spin: 6, control: 7, comfort: 10, durability: 4, tension_stability: 10 },
    description: '세계 최고 수준의 타구감과 장력 유지를 제공하는 내추럴 거트. 하이브리드 메인으로도 폭넓게 활용됩니다.',
    tags: ['컴포트', '최고급', '하이브리드메인'],
  },
  {
    id: 'babolat-rpm-team-125',
    brand: 'Babolat',
    name: 'RPM Team',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'octagon',
    stiffness: 64,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '15,500원/12m',
    specs: { power: 7, spin: 8, control: 7, comfort: 7, durability: 7, tension_stability: 6 },
    description: 'RPM Blast보다 부담을 줄인 스핀형 폴리입니다. 강한 회전 성능은 유지하면서 조금 더 부드러운 응답을 원하는 플레이어에게 어울립니다.',
    tags: ['스핀', '컴포트', '올라운드'],
  },
  {
    id: 'head-hawk-power-125',
    brand: 'Head',
    name: 'Hawk Power',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 68,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '14,000원/12m',
    specs: { power: 8, spin: 7, control: 8, comfort: 6, durability: 8, tension_stability: 7 },
    description: '반발력과 컨트롤의 균형을 노린 라운드 폴리입니다. 빠른 스윙에서 공을 밀어내는 힘과 안정적인 방향성을 함께 제공합니다.',
    tags: ['파워', '컨트롤', '라운드'],
  },
  {
    id: 'msv-focus-hex-118',
    brand: 'MSV',
    name: 'Focus Hex',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'hexagon',
    stiffness: 66,
    arm_friendly: false,
    gauge_mm: 1.18,
    gauge_label: '18 (1.18mm)',
    recommended_tension: '45-52lbs',
    price_band: '10,000원/12m',
    specs: { power: 7, spin: 9, control: 8, comfort: 6, durability: 6, tension_stability: 7 },
    description: '얇은 게이지와 육각 단면으로 스핀 접근성이 좋은 가성비 폴리입니다. 볼을 감아 올리는 느낌과 빠른 반응을 선호하는 플레이어에게 맞습니다.',
    tags: ['스핀', '가성비', '얇은 게이지'],
  },
  {
    id: 'yonex-polytour-force-125',
    brand: 'Yonex',
    name: 'PolyTour Force',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 69,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '16,000원/12m',
    specs: { power: 7, spin: 7, control: 9, comfort: 5, durability: 8, tension_stability: 8 },
    description: '단단하고 정직한 응답을 주는 컨트롤형 폴리입니다. 라켓 헤드 스피드가 충분하고 탄도를 직접 조절하는 플레이어에게 적합합니다.',
    tags: ['컨트롤', '장력유지', '단단함'],
  },
  {
    id: 'big-booster-super-soft-rough-125',
    brand: 'Big Booster',
    name: 'Super Soft Rough',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'rough',
    stiffness: 59,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '44-51lbs',
    price_band: '11,000원',
    specs: { power: 8, spin: 8, control: 6, comfort: 8, durability: 6, tension_stability: 6 },
    description: '거친 표면과 부드러운 타구감을 함께 노린 폴리입니다. 팔 부담을 줄이면서 회전과 반발을 얻고 싶은 입문-중급자에게 잘 맞습니다.',
    tags: ['컴포트', '스핀', '소프트'],
  },
  {
    id: 'solinco-mach-10-125',
    brand: 'Solinco',
    name: 'Mach-10',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 61,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-52lbs',
    price_band: '16,000원/12m',
    specs: { power: 8, spin: 8, control: 7, comfort: 8, durability: 7, tension_stability: 7 },
    description: '솔린코 특유의 공격성을 조금 더 빠르고 편안하게 풀어낸 폴리입니다. 스핀, 반발, 편안함을 모두 챙기는 현대적인 올라운드 성향입니다.',
    tags: ['올라운드', '컴포트', '반발'],
  },
  {
    id: 'tecnifibre-razor-soft-125',
    brand: 'Tecnifibre',
    name: 'Razor Soft',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 60,
    arm_friendly: true,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '45-52lbs',
    price_band: '15,000원/12m',
    specs: { power: 7, spin: 7, control: 8, comfort: 8, durability: 7, tension_stability: 8 },
    description: 'Razor 계열의 정밀한 컨트롤을 부드럽게 다듬은 스트링입니다. 편안함을 해치지 않으면서 안정적인 랠리 품질을 원하는 플레이어에게 적합합니다.',
    tags: ['컨트롤', '컴포트', '장력유지'],
  },
  {
    id: 'restring-vivo-123',
    brand: 'ReString',
    name: 'Vivo',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 63,
    arm_friendly: true,
    gauge_mm: 1.23,
    gauge_label: '17 (1.23mm)',
    recommended_tension: '45-52lbs',
    price_band: '17,500원/12m',
    specs: { power: 8, spin: 7, control: 7, comfort: 8, durability: 7, tension_stability: 7 },
    description: '생동감 있는 반발과 부드러운 접촉감을 우선한 폴리입니다. 깊은 볼을 쉽게 만들고 싶은 중급 플레이어에게 좋은 선택지입니다.',
    tags: ['파워', '컴포트', '올라운드'],
  },
  {
    id: 'restring-sync-125',
    brand: 'ReString',
    name: 'Sync',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 66,
    arm_friendly: false,
    gauge_mm: 1.25,
    gauge_label: '16L (1.25mm)',
    recommended_tension: '46-53lbs',
    price_band: '16,500원/12m',
    specs: { power: 7, spin: 8, control: 8, comfort: 6, durability: 8, tension_stability: 8 },
    description: '반응 속도와 예측 가능한 타구감을 중시한 밸런스형 폴리입니다. 스핀과 컨트롤을 함께 쓰는 베이스라이너에게 어울립니다.',
    tags: ['밸런스', '컨트롤', '장력유지'],
  },
  {
    id: 'restring-zero-123',
    brand: 'ReString',
    name: 'Zero',
    type: '폴리에스터',
    family: 'co-poly',
    shape: 'round',
    stiffness: 62,
    arm_friendly: true,
    gauge_mm: 1.23,
    gauge_label: '17 (1.23mm)',
    recommended_tension: '45-52lbs',
    price_band: '16,500원/12m',
    specs: { power: 7, spin: 8, control: 8, comfort: 7, durability: 7, tension_stability: 8 },
    description: '편안한 폴리 감각과 안정적인 스냅백을 노린 스트링입니다. 기존 폴리가 부담스럽지만 멀티보다 컨트롤을 원하는 플레이어에게 적합합니다.',
    tags: ['컴포트', '스냅백', '컨트롤'],
  },
];
