export const STRING_BRANDS = [
  'Babolat',
  'Head',
  'Kirschbaum',
  'Luxilon',
  'MSV',
  'Pacific',
  'Polyfibre',
  'Prince',
  "Pro's Pro",
  'Signum Pro',
  'Solinco',
  'Tecnifibre',
  'Volkl',
  'Wilson',
  'Yonex',
];

export const STRING_MODELS = {
  Babolat: [
    'RPM Blast',
    'RPM Blast Rough',
    'RPM Soft',
    'RPM Team',
    'SG SpiralTek',
    'Tonic Ball Feel',
    'Tonic+',
    'VS Natural Gut',
    'VS Touch',
    'Xcel',
  ],
  Head: [
    'Gravity',
    'Hawk',
    'Hawk Touch',
    'Lynx',
    'Lynx Edge',
    'Lynx Tour',
    'Rip Control',
    'Velocity MLT',
  ],
  Kirschbaum: [
    'Max Power',
    'Pro Line Evolution',
    'Pro Line II',
    'Super Smash',
    'Versus',
  ],
  Luxilon: [
    '4G',
    '4G Rough',
    '4G Soft',
    'ALU Power',
    'ALU Power Fluoro',
    'ALU Power Rough',
    'ALU Power Soft',
    'ALU Power Spin',
    'Element',
    'Element IR',
    'M2 Pro',
    'Savage',
    'Savage Lime',
  ],
  MSV: [
    'Co. Focus',
    'Co. Focus HEX',
    'Co. Focus HEX Soft',
    'Focus-Hex',
    'Focus-Hex Soft',
    'Focus-Hex Ultra',
    'Hepta-Twist',
  ],
  Pacific: [
    'Classic Natural Gut',
    'PC Pro',
    'Poly Force',
    'Power Line',
    'Tough Gut',
  ],
  Polyfibre: [
    'Cobra',
    'Hexablade',
    'Hextreme',
    'TCS',
    'TCS Rough',
  ],
  Prince: [
    'Beast XP',
    'Duraflex',
    'Lightning XX',
    'Perfection',
    'Premier LT',
    'Synthetic Gut',
    'Tour XP',
    'Warrior',
  ],
  "Pro's Pro": [
    'Blackout',
    'Cyclone Power',
    'Outbreak',
    'Penta Pro',
    'Tenace Pro',
    'Ultraspin',
  ],
  'Signum Pro': [
    'Micronite',
    'Poly Plasma',
    'Poly Plasma Pure',
    'Thunderstorm',
    'Tornado',
    'Triton',
  ],
  Solinco: [
    'Confidential',
    'Heaven',
    'Hyper-G',
    'Hyper-G Soft',
    'Revolution',
    'Tour Bite',
    'Tour Bite Diamond Rough',
    'Tour Bite Soft',
    'Vanquish',
    'Wonder Friend',
    'Wonder Spin',
  ],
  Tecnifibre: [
    'Black Code',
    'Black Code 4S',
    'Black Code Fire',
    'HDMX',
    'Ice Code',
    'Pro Red Code',
    'Pro Red Code Wax',
    'TGV',
    'Triax',
    'X-One Biphase',
  ],
  Volkl: [
    'Cyclone',
    'Cyclone Tour',
    'Power Fiber II',
    'V-Pro',
  ],
  Wilson: [
    "Champion's Choice Duo",
    'Enduro Pro',
    'NXT',
    'NXT Control',
    'NXT Power',
    'Revolve',
    'Revolve Spin',
    'Sensation',
    'Stamina',
  ],
  Yonex: [
    'Poly Tour Fire',
    'Poly Tour Pro',
    'Poly Tour Rev',
    'Poly Tour Spin',
    'Poly Tour Strike',
    'Poly Tour Tough',
  ],
};

export const STRING_TYPES = [
  'Polyester (Co-Poly)',
  'Polyester (Mono)',
  'Multifilament',
  'Natural Gut',
  'Synthetic Gut',
  'Nylon',
];

export const GAUGE_OPTIONS = [
  { value: '1.10mm (19)', label: '1.10mm (19)' },
  { value: '1.15mm (18)', label: '1.15mm (18)' },
  { value: '1.18mm (18)', label: '1.18mm (18)' },
  { value: '1.20mm (17)', label: '1.20mm (17)' },
  { value: '1.24mm (17)', label: '1.24mm (17)' },
  { value: '1.25mm (16L)', label: '1.25mm (16L)' },
  { value: '1.27mm (16)', label: '1.27mm (16)' },
  { value: '1.30mm (16)', label: '1.30mm (16)' },
  { value: '1.35mm (15L)', label: '1.35mm (15L)' },
  { value: '1.40mm (15)', label: '1.40mm (15)' },
];

export const POLYGON_TYPES = ['4각형', '5각형', '6각형', '7각형', '8각형', '별형'];
